### ISSUE TITLE
Timeouts happen immediately

### ISSUE THREAD

**Issue by seglberg** [fortytw2/leaktest#19]
It appears that since the `context.WithTimeout` is called at the beginning of the test, tests which take longer than `timeout` to complete automatically fail. This is because the `Done` channel on the context is already closed by time the test completes. This is problematic for tests which take an non-deterministic amount of time to complete.

I would have expected the timeout value to be the amount of time leaktest waits when the deferred function is executed, not from the moment `Check` is called.

Currently we are getting around the issue by wrapping leaktest functionality:
```go
func CheckTimeout(t *testing.T, dur time.Duration) func() {
    ctx, cancel := context.WithCancel(context.Background())
    fn := leaktest.CheckContext(ctx, t)
    return func() {
        time.AfterFunc(dur, cancel)
	fn()
    }
}
```

**Comment by fortytw2** [comment]
Definitely a bug, will write some test cases for this later and hopefully get it fixed ASAP. Thanks for pointing it out!

**Comment by fortytw2** [comment]
@seglberg do you mind if I just use your implementation for this? 

```
	ctx, cancel := context.WithTimeout(context.Background(), dur)
	fn := CheckContext(ctx, t)
	return func() {
		fn()
		cancel()
	}
```
is the current (wrong) impl

**Comment by seglberg** [comment]
Absolutely!
