### ISSUE TITLE
README example is missing a ()

### ISSUE THREAD

**Issue by pschlump** [fortytw2/leaktest#2]
Example in README should be
```Go
func TestPool(t *testing.T) {
	defer leaktest.Check(t)()

	go func() {
		for {
			time.Sleep(time.Second)
		}
	}()
}
```

Notice the () after the } at the end of the go function -- Just a typo I am certain.

**Comment by fortytw2** [comment]
it's not extra - when you declare an anonymous function in Go, like 

```go
var foo = func() int { return 1 }
// compare this to 
var bar = func() int { return 1 }()
```

in the above example, `foo` is a function that returns an int, but `bar` is a int that equals 1 - so when using the `go` keyword you need to call the function - it's `go foo()` not `go foo`
