### ISSUE TITLE
tip vs the rest

### ISSUE THREAD

**Issue by bep** [fortytw2/leaktest#7]
See https://travis-ci.org/bep/debounce

I don't understand why a leak is reported on tip, but not on <= Go 1.6.

**Comment by fortytw2** [comment]
Definitely smells funky. I'll set up travis on this repo later and see what happens on tip 👌

**Comment by fortytw2** [comment]
Update here - can't reproduce on travis with the tests in this repo right now, I'll look through your code and try to come up with a test case :D

**Comment by belak** [comment]
This might be able to be merged with #9

**Comment by fortytw2** [comment]
closed by https://github.com/fortytw2/leaktest/pull/10
